import { useCallback, useState } from 'react'
import { useFocusEffect } from '@react-navigation/native'
import { StyleSheet, Text, View } from 'react-native'
import { useForm, Controller } from 'react-hook-form'
import { downloadAndShare } from '../services/fileService'
import { getHistory } from '../services/historyService'
import { errorMessage } from '../utils/errorMessage'
import { currentMonthRange, formatDate, formatSignedDuration, formatTime, formatWorkload } from '../utils/format'
import { Button, Card, Field, Loading, Notice, Pagination, Title } from '../components/Ui'
import { Screen } from '../components/Screen'
import { useTheme } from '../contexts/ThemeContext'

function isValidPeriod(startDate, endDate) { const start = new Date(`${startDate}T00:00:00`); const end = new Date(`${endDate}T00:00:00`); return !Number.isNaN(start.getTime()) && !Number.isNaN(end.getTime()) && start <= end && (end - start) / 86400000 <= 90 }
export default function HistoryScreen() {
  const range = currentMonthRange(); const { theme } = useTheme(); const [history, setHistory] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [exporting, setExporting] = useState(false); const [activeRange, setActiveRange] = useState(range); const [offset, setOffset] = useState(0)
  const { control, handleSubmit, getValues, formState: { errors } } = useForm({ defaultValues: range })
  const load = useCallback(async (values, nextOffset = 0) => { try { setLoading(true); setError(''); const response = await getHistory(values.startDate, values.endDate, 10, nextOffset); setHistory(response.data) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [])
  useFocusEffect(useCallback(() => { load(activeRange, offset) }, [activeRange, load, offset]))
  const exportFile = async (format) => { try { setExporting(true); setError(''); const values = getValues(); await downloadAndShare(`/api/history/export.${format}?startDate=${values.startDate}&endDate=${values.endDate}`, `historico-horas.${format}`) } catch (err) { setError(errorMessage(err, 'Não foi possível exportar o arquivo.')) } finally { setExporting(false) } }
  const applyFilter = (values) => { setOffset(0); setActiveRange(values) }
  const changePage = (nextOffset) => { setOffset(nextOffset) }
  return <Screen><Title subtitle="Consulte os dias trabalhados por período.">Histórico</Title><Card><Controller control={control} name="startDate" rules={{ required: 'Informe a data inicial.', validate: (_, values) => isValidPeriod(values.startDate, values.endDate) || 'O período deve ser válido e ter até 90 dias.' }} render={({ field: { value, onChange } }) => <Field label="Data inicial (AAAA-MM-DD)" value={value} onChangeText={onChange} error={errors.startDate?.message} />} /><Controller control={control} name="endDate" rules={{ required: 'Informe a data final.' }} render={({ field: { value, onChange } }) => <Field label="Data final (AAAA-MM-DD)" value={value} onChangeText={onChange} error={errors.endDate?.message} />} /><Button title={loading ? 'Carregando...' : 'Filtrar'} disabled={loading || exporting} onPress={handleSubmit(applyFilter)} /><View style={styles.actions}><Button title="Exportar PDF" variant="secondary" disabled={!history || exporting} onPress={() => exportFile('pdf')} /><Button title="Exportar Excel" variant="secondary" disabled={!history || exporting} onPress={() => exportFile('xlsx')} /></View></Card><Notice message={error} />{loading && !history ? <Loading /> : history && <><View style={styles.summary}><Card style={styles.summaryCard}><Text>Total</Text><Text style={styles.number}>{formatWorkload(history.totalWorkedMinutes)}</Text></Card><Card style={styles.summaryCard}><Text>Saldo</Text><Text style={styles.number}>{formatSignedDuration(history.totalBalanceMinutes)}</Text></Card><Card style={styles.summaryCard}><Text>Banco acumulado</Text><Text style={styles.number}>{formatSignedDuration(history.hourBankMinutes)}</Text></Card><Card style={styles.summaryCard}><Text>Dias trabalhados</Text><Text style={styles.number}>{history.workedDayTotals?.total ?? 0}</Text><Text style={{ color: theme.muted }}>{history.workedDayTotals?.inSchedule ?? 0} na jornada · {history.workedDayTotals?.outsideSchedule ?? 0} fora</Text></Card></View><Card><Text style={[styles.title, { color: theme.text }]}>Dias do período</Text>{history.days.length === 0 ? <Text>Nenhum registro encontrado.</Text> : history.days.map((day) => <View key={day.date} style={[styles.day, { borderBottomColor: theme.border }]}><Text style={{ color: theme.text, fontWeight: '700' }}>{formatDate(day.date)}</Text><Text style={{ color: theme.muted }}>{formatTime(day.firstEntryAt)} — {formatTime(day.lastExitAt)} · {formatWorkload(day.workedMinutes)}</Text><Text style={{ color: day.isComplete ? theme.success : theme.warning }}>{day.isComplete ? `Saldo ${formatSignedDuration(day.balanceMinutes)}` : 'Em andamento'}</Text></View>)}<Pagination pagination={history.pagination} disabled={loading || exporting} onPageChange={changePage} /></Card></>}</Screen>
}
const styles = StyleSheet.create({ actions: { flexDirection: 'row', gap: 8 }, summary: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, summaryCard: { flexGrow: 1, flexBasis: '45%' }, number: { fontSize: 17, fontWeight: '700' }, title: { fontSize: 18, fontWeight: '700' }, day: { gap: 5, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth } })
