import { useCallback, useEffect, useState } from 'react'
import { Pressable, ScrollView, Text, View } from 'react-native'
import { Button, Card, Field, Loading, Notice, Title } from '../components/Ui'
import { Screen } from '../components/Screen'
import { getUserHistory, createUserWorkLog, updateUserWorkLog } from '../services/historyService'
import { listUsers } from '../services/userService'
import { errorMessage } from '../utils/errorMessage'
import { useTheme } from '../contexts/ThemeContext'

function currentMonth() { const now = new Date(); const year = now.getFullYear(); const month = String(now.getMonth() + 1).padStart(2, '0'); return { start: `${year}-${month}-01`, end: `${year}-${month}-${String(new Date(year, now.getMonth() + 1, 0).getDate()).padStart(2, '0')}` } }
function inputValue(instant) { const parts = new Intl.DateTimeFormat('sv-SE', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(instant)); const values = Object.fromEntries(parts.filter((part) => part.type !== 'literal').map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day} ${values.hour}:${values.minute}` }
function instant(value) { return new Date(`${value.replace(' ', 'T')}:00-03:00`).toISOString() }

export default function WorkLogAdjustmentsScreen() {
  const { theme } = useTheme(); const [users, setUsers] = useState([]); const [userId, setUserId] = useState(''); const [history, setHistory] = useState(null); const [form, setForm] = useState({ entryAt: '', exitAt: '' }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const range = currentMonth()
  const load = useCallback(async (id) => { if (!id) return; try { setLoading(true); const response = await getUserHistory(id, range.start, range.end); setHistory(response.data || null) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [range.end, range.start])
  useEffect(() => { listUsers().then((response) => { const items = response.data || []; setUsers(items); setUserId(items[0]?.id || '') }).catch((err) => setError(errorMessage(err))) }, [])
  useEffect(() => { load(userId) }, [load, userId])
  const save = async () => { try { if (!userId || !form.entryAt || !form.exitAt) throw new Error('Informe entrada e saída no formato AAAA-MM-DD HH:MM.'); setSaving(true); setError(''); const payload = { entryAt: instant(form.entryAt), exitAt: instant(form.exitAt) }; const response = editing ? await updateUserWorkLog(userId, editing.id, payload) : await createUserWorkLog(userId, payload); if (!response.success) throw new Error(response.message); setMessage(editing ? 'Registro atualizado.' : 'Registro criado.'); setEditing(null); setForm({ entryAt: '', exitAt: '' }); await load(userId) } catch (err) { setError(errorMessage(err)) } finally { setSaving(false) } }
  const edit = (log) => { if (!log.exitAt) return; setEditing(log); setForm({ entryAt: inputValue(log.entryAt), exitAt: inputValue(log.exitAt) }); setMessage('') }
  if (loading && users.length === 0) return <Loading />
  const logs = history?.days?.flatMap((day) => day.workLogs.map((log) => ({ date: day.date, log }))) || []
  return <Screen><ScrollView contentContainerStyle={{ gap: 16 }}><Title subtitle="Crie ou corrija entrada e saída dos usuários.">Ajustes de ponto</Title><Card><Text style={{ color: theme.text, fontWeight: '700' }}>Usuário</Text>{users.map((user) => <Pressable key={user.id} onPress={() => setUserId(user.id)} style={{ borderWidth: 1, borderColor: theme.border, borderRadius: 8, padding: 10, backgroundColor: userId === user.id ? theme.primary : theme.surface }}><Text style={{ color: userId === user.id ? theme.primaryText : theme.text }}>{user.name} — {user.email}</Text></Pressable>)}</Card><Card><Text style={{ color: theme.text, fontSize: 18, fontWeight: '700' }}>{editing ? 'Editar registro' : 'Novo registro'}</Text><Field label="Entrada (AAAA-MM-DD HH:MM)" value={form.entryAt} onChangeText={(entryAt) => setForm({ ...form, entryAt })} placeholder="2026-07-13 08:00" /><Field label="Saída (AAAA-MM-DD HH:MM)" value={form.exitAt} onChangeText={(exitAt) => setForm({ ...form, exitAt })} placeholder="2026-07-13 17:00" /><Text style={{ color: theme.muted }}>Horários no fuso de São Paulo. Não são permitidos períodos sobrepostos.</Text><Button title={saving ? 'Salvando...' : editing ? 'Salvar alteração' : 'Criar registro'} disabled={saving || !userId} onPress={save} />{editing && <Button title="Cancelar edição" variant="secondary" onPress={() => { setEditing(null); setForm({ entryAt: '', exitAt: '' }) }} />}</Card><Notice message={error || message} type={error ? 'error' : 'success'} /><Card><Text style={{ color: theme.text, fontSize: 18, fontWeight: '700' }}>Registros deste mês</Text>{logs.map(({ date, log }) => <View key={`${date}-${log.id}`} style={{ borderBottomWidth: 1, borderBottomColor: theme.border, paddingVertical: 10, gap: 5 }}><Text style={{ color: theme.text }}>{date}: {inputValue(log.entryAt)} — {log.exitAt ? inputValue(log.exitAt) : 'Em aberto'}</Text><Button title="Editar" variant="secondary" disabled={!log.exitAt || saving} onPress={() => edit(log)} /></View>)}</Card></ScrollView></Screen>
}
